<?xml version="1.0"?>
<package format="3">
  <name>llm_prompt_provider_plugins</name>
  <version>0.1.0</version>
  <description>
    This package provides a prompt provider plugin for different language models
  </description>

  <maintainer email="michael.pritchard@canberra.edu.au">Michael Pritchard</maintainer>
  <maintainer email="mppritchard3@hotmail.com">mik-p</maintainer>

  <author email="michael.pritchard@canberra.edu.au">Michael Pritchard</author>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>prompt_msgs</depend>

  <depend>libpoco-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
