# config for prompt_bridge
/**:
  ros__parameters:
    loop_rate: 10.0
    frame_id: prompt_bridge
    cached_transactions: 10
    offer_service: true
    use_scheme: true
    prompt_provider_plugin: prompt_provider::rest::ChatPromptProvider
    prompt_scheme_plugin: prompt_scheme::DefaultScheme
    
    # provider config
    rest:
      SinglePromptProvider:
        uri: http://10.0.0.246:11434/api/generate
        # uri: http://ollama:11434/api/generate docker container with name 'ollama'
        # uri: http://ollama:11434/v1/completions (openai api compat version)
        method: POST
        auth_type: Bearer

      ChatPromptProvider:
        uri: http://10.0.0.246:11434/api/chat
        # uri: http://ollama:11434/api/chat docker container with name 'ollama'
        # uri: http://ollama:11434/v1/completions (openai api compat version)
        method: POST
        auth_type: Bearer
