# config for prompt_bridge
/**:
  ros__parameters:
    loop_rate: 10.0
    frame_id: prompt_bridge
    cached_transactions: 10
    offer_service: true
    prompt_provider_plugin: prompt_provider::RestPromptProvider
    prompt_scheme_plugin: prompt_schemes::BTScheme

    # provider config
    RestPromptProvider:
      # use ollama as example in docker container with name 'ollama'
      uri: http://ollama:11434/api/generate
      # uri: http://ollama:11434/v1/completions (oai api compat version)
      method: POST
      auth_type: Bearer

    # scheme config
    BTScheme:
      prompt_option_keys: [stream, model]
      prompt_options:
        stream:
          value: false
          type: bool
        model:
          value: llama3.1:8b
