#pragma once

// #include <capabilities2_msgs/action/capability_action.hpp>
#include <capabilities2_runner/action_runner.hpp>
#include <pluginlib/class_list_macros.hpp>
#include <prompt_schemes/bt_scheme.hpp>

namespace prompt_bridge
{
/** */
class BTSchemeDoc
{
};

/**
 * @brief supervise capability runner
 *
 * this class is a wrapper around the capabilities2 action runner
 * it is used to supervise a plan generated by the prompt plan action
 *
 */
template <typename Doc>
class PromptRunner : public capabilities2_runner::ActionRunner
{
public:
  PromptCapRunner() : ActionRunner<capabilities2_msgs::action::CapabilityAction>()
  {
  }
};

// scheme type
typedef prompt_bridge::PromptRunner<prompt_bridge::BTSchemeDoc> BTPromptRunner;

}  // namespace prompt_bridge

// register the action runner
PLUGINLIB_EXPORT_CLASS(prompt_bridge::BTPromptRunner, capabilities2_runner::RunnerBase)
